/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "svngynhkmxefudqvzbps"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2bmd5bmhrbXhlZnVkcXZ6YnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NjA3MTcsImV4cCI6MjA5NTQzNjcxN30.fW80MtgC07aOsVoK5n3i1lOXU3QqC7CHNurcB-EN-EI"